---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
spec:
  template:
    spec:
      nodeSelector:
        dedicated: nlp
      tolerations:
      - key: dedicated
        operator: Equal
        value: nlp
        effect: NoSchedule
