---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
spec:
  template:
    spec:
      containers:
      - name: rasa
        resources:
          requests:
            cpu: "0.5"
            memory: "3Gi"
